### PR TITLE
Update for Julia 1.0

### PR DESCRIPTION
**Pull request by timbitz**
Tests pass on my machine-- this should work ;)

### CODE REVIEW

**Comment by timbitz** [comment]
Hey @quinnj, I think this is ready to merge and tag if you're okay with it?

**Review by quinnj — APPROVED** [review]
Thanks for the updates here! I actually can't remember if I ever registered this package. Is it in METADATA? Do you want to take it over? I haven't used it since doing the initial writeup.

**Comment by timbitz** [comment]
Hey @quinnj— yah it’s registered in METADATA.jl.  I’m more than happy to take it over for you if you’d like!

**Comment by quinnj** [comment]
Cool. I can either transfer the whole repo somewhere for you, or just give you full admin access here; whatever you'd prefer. If I transfer the repo, we'd probably have to update METADATA to point to the new url, so it's a little easier to just keep it here and give you admin.

**Comment by timbitz** [comment]
Yah let's just keep it here, Thanks!.  Is Attobot set up on this repo?-- it'd be good to tag a v1.0 release.

**Pull request merged**
