### PR TITLE
needed sorted suffix arrays in pure Julia, so I revived this

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Not sure about the changes I made, although it mostly seems to help clarify. The last one changes the API considerably to just providing the sorted suffix array for an array of integer values, rather than for a string. Since you can always get the suffix array for `codeunits(s)` that seems sufficient to me and simpler. If you use the suffix array to search for a substring, that will work even with non-ASCII strings since UTF-8 is self-synchronizing: a code unit sequence matches if and only if the substring matches. For UTF-16 you'd want to do something similar but where the code units are UInt16 values (which is what they naturally are) since UTF-16 is self-synchronizing at the code unit level but _not_ at the byte level.

### CODE REVIEW

**Comment by quinnj** [comment]
Great stuff; I'm fine w/ whatever changes you'd like to make and if we want to move this anywhere else, I'm on board.

**Comment by StefanKarpinski** [comment]
Any sense of how many people may have been relying on the old API? It would be good to add efficient substring search etc. with a higher level API, but it might be good to separate sorted suffix array computation from that, since they're perfectly decoupled as far as I can tell: you don't care how you got a sorted suffix array once you have one.

**Comment by quinnj** [comment]
I doubt there are many users, but we could do a 1.0 release in any case w/ maybe a discourse announcement of changes just in case.

**Comment by StefanKarpinski** [comment]
Are you cool with this API? It occurred to me that this method:

https://github.com/quinnj/SuffixArrays.jl/pull/10/files#diff-7a19eadc6a1bf68e9259fa78bc42794eR19

which is currently just for UTF-8 string types is actually completely general for all string types as long as the computation is done in terms of code units and the string encoding is self-synchronizing, which we do [explicitly require](https://github.com/JuliaLang/julia/blob/2c43528f39dfc22d2b02a800c27dcd09b002cb9f/base/strings/basic.jl#L19) for all implementations of abstract string.

**Comment by quinnj** [comment]
Yeah, definitely cool with that API. TBH, I haven't used this much over the years since I originally did the port, but it's nice to have it updated and made more useful.

**Comment by StefanKarpinski** [comment]
Ok, I broadened the string method and added tests to make sure it works for UTF-8 and UTF-16.

**Comment by StefanKarpinski** [comment]
Ok, let's transfer this to JuliaArrays: @mbauman, can you add @quinnj to https://github.com/orgs/JuliaArrays/people with sufficient privileges so that he can transfer the repo? I think it's enough to be a normal member so long as members can create repos. I would also like to be added so I can help maintain this package (register a version, etc.). There's a slight question of whether this actually belongs in JuliaArrays or JuliaStrings, since it's mostly useful for substring search, but it mainly operates on arrays of values, so it's a little hard to say.

**Comment by StefanKarpinski** [comment]
I guess if could also go in https://github.com/JuliaCollections along with SortingAlgorithms, etc.

**Comment by mbauman** [comment]
Jacob's already in JuliaArrays (or someone beat me to it), but I think it might be a better fit for Collections since it doesn't export a `SuffixArray <: AbstractArray`.

**Comment by StefanKarpinski** [comment]
True. Although it could potentially do that: if you pair an array with its suffix array, then you get an array that can do very fast substring queries, which could be a useful data type. Are you looking for substings a lot in some array and it's too slow? Just pass in `SuffixArray(a)` instead of `a` and your code will magically get faster (in exchange for some extra memory). Of course, then you can't just mutate your array willy nilly anymore, but that's fairly common for other array types.

**Comment by StefanKarpinski** [comment]
It's somewhat tempting to rename this to `SuffixSorting` which implements the sorting part, while `SuffixArrays` could define a type that wraps an array with its suffix array to provide an array with fast substring queries. Or maybe I'm overthinking it.

**Comment by StefanKarpinski** [comment]
Changed this so that the project UUID is the METADATA-compatible one since it's the same package with a new API.

**Pull request merged**
